name: Madog
schemes:
  Madog:
    build:
      targets:
        Madog: all
        MadogContainers_iOS: all
        TestApp: [run]
    test:
      gatherCoverageData: true
      coverageTargets:
        - MadogContainers_iOS
      targets: 
        - MadogContainersTests_iOS
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
packages:
  MadogCore:
    url: https://github.com/cerihughes/madog-core
    majorVersion: 2.0.0
  KIF:
    url: https://github.com/kif-framework/KIF
    majorVersion: 3.8.0
targets:
  Madog:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: Madog/Info.plist
    sources:
      - Madog
    dependencies:
      - package: MadogCore
      - target: MadogContainers_iOS
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogContainers_iOS:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: MadogContainers_iOS/Info.plist
    sources:
      - MadogContainers_iOS
    dependencies:
      - package: MadogCore
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogContainersTests_iOS:
    type: bundle.unit-test
    platform: iOS
    settings:
      TEST_TARGET_NAME: TestApp
    sources:
      - MadogContainersTests_iOS
    dependencies:
      - package: MadogCore
      - package: KIF
      - target: MadogContainers_iOS
      - target: TestApp
  TestApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: TestApp/Info.plist
    sources: TestApp
