name: Madog
schemes:
  Madog:
    build:
      targets:
        MadogCore: all
        MadogContainers_iOS: all
        MadogCoreTests: [test]
        TestApp: [run]
    test:
      gatherCoverageData: true
      coverageTargets:
        - MadogCore
        - MadogContainers_iOS
      targets: 
        - MadogCoreTests
        - MadogContainersTests_iOS
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
packages:
  KIF:
    url: https://github.com/kif-framework/KIF
    exactVersion: 3.8.6
targets:
  MadogCore:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: MadogCore/Info.plist
    sources:
      - MadogCore
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogContainers_iOS:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: MadogContainers_iOS/Info.plist
    sources:
      - MadogContainers_iOS
    dependencies:
      - target: MadogCore
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogCoreTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      TEST_TARGET_NAME: TestApp
    sources:
      - MadogCoreTests
    dependencies:
      - target: MadogCore
      - target: TestApp
      - package: KIF
  MadogContainersTests_iOS:
    type: bundle.unit-test
    platform: iOS
    settings:
      TEST_TARGET_NAME: TestApp
    sources:
      - MadogContainersTests_iOS
      - SampleApp/SampleApp/Custom UI
    dependencies:
      - target: MadogCore
      - target: TestApp
      - package: KIF
  TestApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: TestApp/Info.plist
    sources: TestApp
