name: SampleApp
schemes:
  SampleApp:
    build:
      targets:
        SampleApp: all
        SampleAppUITests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - SampleApp
      targets: 
        - SampleAppUITests
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
projectReferences:
  Madog:
    path: ../Madog.xcodeproj
targets:
  SampleApp:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: SampleApp/Info.plist
    sources:
      - SampleApp
    dependencies:
      - target: Madog/MadogCore
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  SampleAppUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      TEST_TARGET_NAME: SampleApp
    sources: SampleAppUITests
    dependencies:
      - target: SampleApp
