name: Build Sample App on Xcode 15.0.1 iOS 17.0.1

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        xcode: [14.3.1, 15.0.1]
        include:
          - ios: 16.4
            xcode: 14.3.1
          - ios: 17.0.1
            xcode: 15.0.1

    runs-on: macos-13

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-sample-app-xcode${{ matrix.xcode }}-

      # Install dependencies
      - run: brew install swiftlint xcodegen || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build sample app
      - run: set -o pipefail
      - run: xcodegen
      - run: cd SampleApp; xcodegen
      - run: xcodebuild test -project SampleApp/SampleApp.xcodeproj -scheme SampleApp -destination "OS=${{ matrix.ios }},name=iPhone 14" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
