name: Test Xcode 12.4 iOS 13.7

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_11.7.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 13.7.simruntime

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode12_4-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode12_4-

      # Install dependencies
      - run: brew install swiftlint || true
      - run: brew outdated swiftlint || brew upgrade swiftlint

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: xcodebuild clean test -project Madog.xcodeproj -scheme Madog -destination "OS=13.7,name=iPhone 11" -destination "OS=13.7,name=iPad (7th generation)" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13