name: Build Sample App on Xcode 15.0.1 iOS 17.0.1

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode14_2-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-sample-app-xcode15_0_1-

      # Install dependencies
      - run: brew install swiftlint xcodegen || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build sample app
      - run: set -o pipefail
      - run: xcodegen
      - run: cd SampleApp; xcodegen
      - run: xcodebuild clean test -project SampleApp/SampleApp.xcodeproj -scheme SampleApp -destination "OS=17.0.1,name=iPhone 14" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
