name: Build sample app

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        xcode: ["14.3.1", "15.4"]
        include:
          - ios: "16.4"
            xcode: "14.3.1"
          - iphone: "iPhone 14"
            xcode: "14.3.1"
          - ios: "17.5"
            xcode: "15.4"
          - iphone: "iPhone 15"
            xcode: "15.4"

    runs-on: macos-14

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-sample-app-xcode${{ matrix.xcode }}-${{ hashFiles('SampleApp/project.yml') }}

      # Install dependencies
      - run: brew install swiftlint xcodegen || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build sample app
      - run: set -o pipefail
      - run: xcodegen
      - run: cd SampleApp; xcodegen
      - run: xcodebuild clean test -project SampleApp/SampleApp.xcodeproj -scheme SampleApp -clonedSourcePackagesDirPath SPM -resultBundlePath coverage.xcresult -destination "OS=${{ matrix.ios }},name=${{ matrix.iphone }}" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-session.xcresult
          path: ${{ github.workspace }}/coverage.xcresult
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            xcode: true
            xcode_archive_path: ${{ github.workspace }}/coverage.xcresult
