name: Test Xcode 14.2 iOS 16.2

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_14.2.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode14_2-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode14_2-

      # Install dependencies
      - run: brew install swiftlint xcodegen || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: xcodegen
      - run: xcodebuild clean test -project Madog.xcodeproj -scheme Madog -destination "OS=16.2,name=iPhone 11" -destination "OS=16.2,name=iPad (10th generation)" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
