name: Test Xcode 15.0.1 iOS 17.0

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13-arm64

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode15_0_1-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode15_0_1-

      # Install dependencies
      - run: brew install swiftlint xcodegen || true
      - run: brew outdated swiftlint || brew upgrade swiftlint
      - run: brew outdated xcodegen || brew upgrade xcodegen

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: xcodegen
      - run: xcodebuild clean test -project Madog.xcodeproj -scheme Madog -resultBundlePath coverage.xcresult -destination "OS=17.0,name=iPhone 14" -destination "OS=17.0,name=iPad (10th generation)" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
            xcode: true
            xcode_archive_path: ${{ github.workspace }}/coverage.xcresult
