name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-11

    steps:
      # Xcode select
      - run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      # Caching
      - name: SPM Cache
        uses: actions/cache@v2
        with:
          path: SPM
          key: ${{ runner.os }}-spm-xcode12_4-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode12_4-

      # Install dependencies
      - run: brew install swiftlint || true
      - run: brew outdated swiftlint || brew upgrade swiftlint

      # Checkout
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      # Build and test
      - run: set -o pipefail
      - run: mkdir build
      - run: xcodebuild clean test -project Madog.xcodeproj -scheme Madog -destination "OS=14.4,name=iPhone 11" -destination "OS=14.4,name=iPad (8th generation)" -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13

      # Build SPM
      - run: swift package generate-xcodeproj --output MadogSPM.xcodeproj
      - run: xcodebuild clean build -project MadogSPM.xcodeproj -scheme Madog-Package -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64

      # Build sample app
      - run: xcodebuild clean build -project SampleApp/SampleApp.xcodeproj -scheme SampleApp -sdk iphonesimulator CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64